# When processing data, drop antibodies with more than this many sites
# of escape that is with more than `max_sig_sites` sites with escape
# of at least `sig_escape_threshold`.
filter_antibodies:
  sig_escape_threshold: 0.1
  max_sig_sites: 40

# sites to show in plot
sites:
  start: 331
  end: 531

# initial mutation escape strength
init_mutation_escape_strength: 2.0

# initial value of weight by negative log IC50
init_weight_by_neg_log_IC50: true

# initial value of study
init_study: any

# initial value of binds
init_binds: any

# options for study, matching name used in data to display name
studies:
  repeated_2023: Yisimayi et al, 2023, bioRxiv
  imprinted_2022: Cao et al, 2022, Nature

# initial value of virus
init_virus: XBB

# initial value of antibody sources
init_sources:
  include_exclude: exclude  # does `sources` list sources to include or exclude?
  sources:
    - SARS convalescents
