# -------------------------------------------
# Configuration for processing data
# -------------------------------------------

# When processing data, drop antibodies with more than this many sites
# of escape that is with more than `max_sig_sites` sites with escape
# of at least `sig_escape_threshold`.
filter_antibodies:
  sig_escape_threshold: 0.1
  max_sig_sites: 40

# To limit plot size, drop escape values less than this after normalizing to one
drop_escape_below: 0.02

# When processing data, only keep viruses with IC50s measured against at
# least this many antibodies
virus_min_antibodies_w_ic50: 1000

# When processing data, we provide antibody re-weightings for some
# groupings. These are designed to account for the instance when
# the antibodies isolated are not representative of their actual frequencies.
antibody_reweighting:
  repeated_2024:
    # these are the re-weightings used in https://doi.org/10.1101/2023.05.01.538516
    #  89% cross-reactive mAbs for BA.5/BF.7 BTI cohorts and 51% for reinfection
    # cohorts, as determined by unbiased characterization of mAbs using ELISA
    cross_reactive_weights:
      BA.5 convalescents: 0.89
      BF.7 convalescents: 0.89
      BA.1 convalescents reinfection: 0.51
      BA.2 convalescents reinfection: 0.51

# -------------------------------------------
# Configuration for escape calculator
# -------------------------------------------

# sites to show in plot
sites:
  start: 331
  end: 531

# initial mutation escape strength
init_mutation_escape_strength: 2.0

# initial value of weight by negative log IC50
init_weight_by_neg_log_IC50: true

# initial value of study
init_study: any

# options for study, matching name used in data to display name
studies:
  evolving_2024: Jian et al, 2024, Nature
  repeated_2024: Yisimayi et al, 2024, Nature
  imprinted_2022: Cao et al, 2022, Nature

# initial value of virus
init_virus: KP.3

# initial value of antibody sources
init_sources:
  include_exclude: exclude  # does `sources` list sources to include or exclude?
  sources:
    - SARS convalescents

# re-weight antibodies from non-representative sources?
init_reweight: true
