name: SARS2-RBD-escape-calc
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - altair=5.0.0
  - biopython=1.81
  - git-lfs
  - jupyter_contrib_nbextensions
  - jupyterlab
  - markdown=3.4.3
  - matplotlib
  - nbstripout
  - openpyxl
  - pandas=2.0
  - pdoc=13.1.1
  - python=3.10
  - python-markdown-math=0.8
  - snakemake=7.25
  - vl-convert-python=0.9.0
  - xlrd
