name: SARS2-RBD-escape-calc
channels:
  - conda-forge
  - bioconda

dependencies:
  - altair=5.4.1
  - biopython=1.84
  - git-lfs
  - jupyterlab
  - markdown=3.4.3
  - matplotlib
  - nbstripout
  - openpyxl
  - pandas=2.2
  - pdoc=13.1.1
  - python=3.11
  - python-markdown-math=0.8
  - xlrd
